### ISSUE TITLE
The demo.ipynb doesn't work.

### ISSUE THREAD

**Issue by ShotDownDiane** [ForestsKing/ChatTime#1]
I tried to run the demo.ipynb, but it seems to be missing the data preprocessing code, which causes the traffic dataset downloaded from Google Drive to be processed incorrectly.

Here is the code:
````
dataset = "Traffic"
df = pd.read_csv(f"./dataset/{dataset}.csv")
temp=df.to_numpy()
temp=temp[:,1:]
temp=temp.astype(float)
hist_len = 120
pred_len = 24

# 滑动窗口函数
def sliding_window(data, window_size):
    return [data[i:i+window_size] for i in range(len(data) - window_size + 1)]

samples=np.array(sliding_window(temp,144))
hist_data=samples[0,:120,:]
pred_data=samples[0,120:,:]
print(hist_data.shape)
print(pred_data.shape)
model = ChatTime(hist_len=hist_len, pred_len=pred_len, model_path=model_path)
print("loading finish!")
out = model.predict(hist_data)
````

Here is the output:
![image](https://github.com/user-attachments/assets/7ab04f86-df63-4583-82f2-9684dab499d7)

What should i do to make it run correctly?

**Comment by ForestsKing** [comment]
Thank you for your interest in our work. Similar to Chronos, ChatTime currently supports only single-dimensional time series analysis.
